import type { Article, ArticlePriceTable, ArticleSection } from "@/lib/site";

const section = (heading: string, body: string[], tips?: string[]): ArticleSection => ({ heading, body, tips });
const priceTable = (note: string, rows: ArticlePriceTable["rows"]): ArticlePriceTable => ({ asOf: "12 August 2026", note, rows });
const article = (input: Omit<Article, "image">): Article => ({ ...input, readTime: Math.max(input.readTime, 10), image: `/images/articles/${input.slug}.webp` });

export const expandedArticles: Article[] = [
  article({
    slug: "australia-travel-cost-2026", title: "How much does it really cost to travel Australia in 2026?", description: "A practical daily budget for backpackers, campers, road trippers and travellers who want a little more comfort.", category: "Costs & budget", region: "Australia", readTime: 13,
    places: ["Sydney", "Melbourne", "Brisbane", "Perth", "Regional Australia"], imageAlt: "Traveller planning an Australian road trip budget", intro: "Australia can be travelled leanly, comfortably or extravagantly, but the honest total depends on how often you move. These dated benchmarks combine food, accommodation, local transport and a modest activity allowance before long-distance travel.",
    priceTable: priceTable("Illustrative daily totals assembled from the dated component prices in this guide. Long-distance transport, vehicle hire and international flights are separate.", [
      { label: "Low-cost camper or hostel traveller", audLow: 85, audHigh: 135, unit: "per person/day" },
      { label: "Mixed-budget independent traveller", audLow: 160, audHigh: 260, unit: "per person/day" },
      { label: "Comfortable hotel road trip", audLow: 290, audHigh: 520, unit: "per person/day" },
      { label: "Two-week low-cost trip", audLow: 1190, audHigh: 1890, unit: "per person" },
      { label: "Four-week mixed-budget trip", audLow: 4480, audHigh: 7280, unit: "per person" },
    ]),
    sections: [
      section("Build the daily number from real components", ["Start with the bed or campsite, then add groceries, eating out, local transport and the average cost of paid experiences. Keeping these lines separate makes the estimate easier to update when one part changes.", "Vehicle travellers should calculate fuel from kilometres and consumption instead of hiding it inside a daily allowance. A fast lap costs more than a slower trip even when the nightly rate is identical."]),
      section("Why one Australian average misleads", ["Sydney, remote roadhouses, tropical dry-season towns and school-holiday beaches can all sit above an ordinary regional benchmark. Promotions and longer stays can move the opposite way.", "Use the table as a scenario tool, then replace each line with quotes for the dates and route you actually want."], ["Price the exact dates", "Separate vehicle hire", "Keep an emergency reserve"]),
      section("A budget that survives a changed plan", ["Hold at least one legal paid-night option and enough money for an extra tank of fuel. Free camping does not remove the need for showers, laundry, water, repairs or the occasional full-service reset.", "Review actual spending every few days. Correcting a small drift in week one is easier than cancelling the best part of the trip in week four."])
    ],
    sources: [
      { label: "Nomads.com Australian cost-of-living comparison", url: "https://nomads.com/cost-of-living/" },
      { label: "Tourism Australia budget guide", url: "https://www.australia.com/en-sg/facts-and-planning/about-australia/australia-on-budget.html" },
      { label: "Numbeo Australia cost benchmarks, June 2026", url: "https://www.numbeo.com/cost-of-living/country_result.jsp?country=Australia" },
      { label: "Reserve Bank of Australia exchange rates", url: "https://www.rba.gov.au/statistics/frequency/exchange-rates.html" },
    ]
  }),
  article({
    slug: "australia-grocery-prices-2026", title: "Australia grocery prices in 2026: a real supermarket budget", description: "Current price ranges for milk, eggs, bread, meat, fruit and vegetables, plus a sensible weekly food plan.", category: "Costs & budget", region: "Australia", readTime: 12,
    places: ["Sydney", "Melbourne", "Aldi", "Coles", "Woolworths"], imageAlt: "Fresh food and groceries at an Australian market", intro: "Self-catering is the simplest way to control a long Australian travel budget. The national ranges below are community-contributed June 2026 benchmarks, useful for scale but not a promise of today’s shelf price in every suburb or remote town.",
    priceTable: priceTable("National community-contributed ranges updated June 2026. Brand, promotion, season, city and remote freight can change the shelf price.", [
      { label: "Milk", audLow: 1.55, audHigh: 4, unit: "1 litre" }, { label: "Bread", audLow: 2.19, audHigh: 6, unit: "500 g loaf" },
      { label: "Eggs", audLow: 4.2, audHigh: 10.2, unit: "12" }, { label: "Chicken fillets", audLow: 8, audHigh: 18.15, unit: "1 kg" },
      { label: "Beef", audLow: 12, audHigh: 35, unit: "1 kg" }, { label: "Apples", audLow: 3.5, audHigh: 7, unit: "1 kg" },
      { label: "Tomatoes", audLow: 3.5, audHigh: 10, unit: "1 kg" },
    ]),
    sections: [
      section("What a road-trip basket needs", ["Build around breakfast, portable lunches and two or three dinners that share ingredients. Oats, bread, eggs, rice or pasta, vegetables and a flexible protein waste less space than a different recipe every night.", "Buy small quantities when refrigeration is weak. A cheap bulk pack is expensive if heat, ice melt or a long driving day makes it unsafe."]),
      section("City prices and remote prices", ["Large supermarkets create more competition and promotional choice. Remote stores and roadhouses may carry fewer sizes at higher prices because transport and stock turnover are different.", "Restock before remote legs, but respect interstate biosecurity restrictions on fruit, vegetables, honey, plants and other regulated items."], ["Compare unit prices", "Plan fridge capacity", "Check border restrictions"]),
      section("A realistic weekly figure", ["A careful solo traveller cooking most meals might start with an indicative A$80–A$140 weekly grocery range, then adjust for diet, appetite and location. Premium meat, convenience foods and remote purchases lift it quickly.", "Keep a separate allowance for coffee, takeaway and shared meals. Calling every food purchase a grocery hides the choices that are easiest to change."])
    ],
    sources: [{ label: "Numbeo Australia price ranges, updated June 2026", url: "https://www.numbeo.com/cost-of-living/country_result.jsp?country=Australia" }, { label: "Australian interstate quarantine guidance", url: "https://www.interstatequarantine.org.au/" }, { label: "Reserve Bank of Australia exchange rates", url: "https://www.rba.gov.au/statistics/frequency/exchange-rates.html" }]
  }),
  article({
    slug: "eating-out-australia-prices-2026", title: "Eating out in Australia in 2026: meal, takeaway and coffee prices", description: "What casual meals, fast food, coffee and a mid-range dinner actually cost, with three daily food budgets.", category: "Costs & budget", region: "Sydney benchmark", readTime: 11,
    places: ["Sydney", "Melbourne", "Brisbane", "Regional towns"], imageAlt: "Outdoor cafe meal in an Australian city", intro: "A city meal can be a quick counter lunch or the largest line in the day’s budget. Sydney provides a useful higher-cost benchmark, while Tourism Australia’s guide offers a broader starting point for restaurant planning.",
    priceTable: priceTable("Sydney community-contributed ranges updated June 2026. Waterfronts, resorts, airports, events and table service can cost more.", [
      { label: "Inexpensive restaurant meal", audLow: 18, audHigh: 40, unit: "per person" }, { label: "Fast-food combo", audLow: 15, audHigh: 18.5, unit: "per person" },
      { label: "Cappuccino", audLow: 4.9, audHigh: 7, unit: "one cup" }, { label: "Soft drink", audLow: 3, audHigh: 5, unit: "330 ml" },
      { label: "Mid-range meal for two", audLow: 80, audHigh: 200, unit: "three courses" },
    ]),
    sections: [
      section("Three workable food styles", ["Self-catering with one purchased coffee or snack keeps the daily total lowest. A mixed day adds one casual meal, while a restaurant-heavy day can exceed the accommodation cost before drinks.", "Breakfast and lunch are often easier to control than dinner. Carrying food also prevents a late arrival from becoming an expensive search near a tourist strip."]),
      section("Read the menu total properly", ["Check whether weekend or public-holiday surcharges apply and whether a card fee appears at payment. Shared plates, sides and drinks can move a seemingly ordinary main course well beyond its headline.", "Remote cafes and small towns have different supply costs and opening hours. Treat a published city range as a benchmark, not an entitlement."], ["Check surcharges", "Keep a backup meal", "Budget drinks separately"]),
      section("Where eating out earns its place", ["Spend deliberately on meals tied to the destination, then use simple groceries on transfer days. This creates room for local seafood, bakeries or produce without making every day expensive.", "Track the actual amount for a few days. Visitors often remember the main-course price but forget coffee, snacks and delivery fees."])
    ],
    sources: [{ label: "Numbeo Sydney prices, updated June 2026", url: "https://www.numbeo.com/cost-of-living/in/Sydney" }, { label: "Tourism Australia budget guide", url: "https://www.australia.com/en-sg/facts-and-planning/about-australia/australia-on-budget.html" }, { label: "Reserve Bank of Australia exchange rates", url: "https://www.rba.gov.au/statistics/frequency/exchange-rates.html" }]
  }),
  article({
    slug: "alcohol-coffee-drink-prices-australia", title: "Beer, wine, coffee and drink prices in Australia", description: "A clear comparison of pub, cafe and bottle-shop prices so drinks do not quietly take over the travel budget.", category: "Costs & budget", region: "Australia", readTime: 10,
    places: ["Sydney", "Bottle shops", "Pubs", "Cafes"], imageAlt: "Australian cafe drinks on a table", intro: "Drinks are easy to underestimate because they arrive one at a time. Current community price ranges show the difference between a bottle-shop purchase, a cafe stop and a round in a city pub.",
    priceTable: priceTable("Community-contributed Australia and Sydney ranges updated June 2026. Serving size, venue, promotion and location vary.", [
      { label: "Cappuccino", audLow: 4.9, audHigh: 7, unit: "one cup" }, { label: "Pub draught beer", audLow: 7, audHigh: 16, unit: "one serving" },
      { label: "Mid-range wine", audLow: 12, audHigh: 29, unit: "750 ml retail" }, { label: "Domestic beer equivalent", audLow: 3.41, audHigh: 11.6, unit: "500 ml retail" },
      { label: "Soft drink", audLow: 3, audHigh: 5, unit: "330 ml venue" },
    ]),
    sections: [section("Retail and venue prices are different products", ["A pub price includes the venue, staff and service rather than only the liquid. Compare like with like and do not describe a bottle-shop equivalent as the price of a poured drink.", "Happy hours and promotions are temporary. Build the budget from the ordinary range, then treat a discount as margin." ]), section("Alcohol and the driving day", ["The safest road-trip plan separates drinking from driving completely. Legal blood-alcohol limits differ by licence and vehicle class, and some drivers must have zero BAC.", "Choose a designated non-drinking driver, stay overnight or use transport. Never turn a conversion table into a drinking allowance."], ["Never drink and drive", "Check local restrictions", "Carry water"]), section("Control the quiet daily total", ["Two coffees and two venue drinks each day can become a substantial weekly amount. Decide which stops matter rather than buying by habit.", "Keep drinking water accessible and refill legally. In hot conditions, hydration and shade belong in the safety plan, not the entertainment budget."])],
    sources: [{ label: "Numbeo Sydney drink prices", url: "https://www.numbeo.com/cost-of-living/in/Sydney" }, { label: "Numbeo Australia retail ranges", url: "https://www.numbeo.com/cost-of-living/country_result.jsp?country=Australia" }, { label: "NSW alcohol and driving guidance", url: "https://www.nsw.gov.au/driving-boating-and-transport/roads-safety-and-rules/safe-driving/alcohol-and-drugs" }]
  }),
  article({
    slug: "accommodation-costs-australia-2026", title: "Accommodation costs in Australia: hostels, hotels and comfortable stays", description: "Realistic price bands from a dorm bed to a boutique hotel, plus the dates and extras that change the total.", category: "Costs & budget", region: "Australia", readTime: 11,
    places: ["Hostels", "Motels", "Hotels", "Holiday parks", "Resorts"], imageAlt: "Australian coastal accommodation at sunset", intro: "The room is often the largest fixed cost of an Australian trip. Tourism Australia’s planning benchmarks show an enormous ladder, from simple shared accommodation to premium resorts.",
    priceTable: priceTable("Tourism Australia planning benchmarks. These are indicative starting prices, not live quotes for every date.", [
      { label: "Hostel dorm bed", audLow: 20, audHigh: 55, unit: "per person/night" }, { label: "Private hostel room", audLow: 55, audHigh: 85, unit: "per person/night" },
      { label: "Last-minute hotel", audLow: 100, audHigh: 200, unit: "per room/night" }, { label: "Boutique hotel", audLow: 250, audHigh: 400, unit: "per room/night" },
      { label: "Luxury resort", audLow: 600, audHigh: 1000, unit: "per room/night" },
    ]),
    sections: [section("Compare the total stay", ["A lower room rate can lose its advantage after parking, linen, breakfast, booking fees or a distant location. Compare the final amount for the same number of people and nights.", "A private room priced per person and a hotel priced per room are not directly comparable until occupancy is included." ]), section("Peak dates change everything", ["School holidays, festivals, sporting events and dry-season demand can multiply rates. Coastal summer weekends and small gateway towns deserve early checks.", "Use refundable terms where uncertainty is real, then record the cancellation deadline beside the trip stop."], ["Compare identical dates", "Read cancellation terms", "Include parking"]), section("Mix accommodation types", ["A full-service room after several camping nights can solve laundry, charging, weather and rest in one purchase. It can be better value than forcing an unsuitable cheap night.", "Reserve premium spending for places where the property itself adds to the experience rather than using it automatically on transfer nights."])],
    sources: [{ label: "Tourism Australia budget guide", url: "https://www.australia.com/en-sg/facts-and-planning/about-australia/australia-on-budget.html" }, { label: "Tourism Australia accommodation directory", url: "https://www.australia.com/en/facts-and-planning/planning-tools/find-accommodation.html" }, { label: "Reserve Bank of Australia exchange rates", url: "https://www.rba.gov.au/statistics/frequency/exchange-rates.html" }]
  }),
  article({
    slug: "camping-fees-australia-2026", title: "Camping fees in Australia: national parks versus holiday parks", description: "What simple, serviced and powered camps can cost, and what each nightly rate may or may not include.", category: "Costs & budget", region: "Australia", readTime: 12,
    places: ["Parks Victoria", "Tidal River", "Harrington", "Sandstone Point", "Holiday parks"], imageAlt: "Caravan and tent at an Australian campground", intro: "A campsite can be a few dollars per person or more than a basic room. The price reflects location, facilities, season, booking conditions and whether the operator charges per site or per guest.",
    priceTable: priceTable("Government schedule and dated commercial promotional examples. Park entry, booking fees, extra guests and vehicles may be separate.", [
      { label: "Selected hike-in park camp", audLow: 6.6, unit: "per person/night" }, { label: "Mid-category park camp", audLow: 17.8, unit: "per site/night" },
      { label: "Higher-service park camp", audLow: 31.8, audHigh: 35.1, unit: "per site/night" }, { label: "Tidal River peak powered site", audLow: 43.1, unit: "per site/night" },
      { label: "Commercial powered-site offer", audLow: 39, audHigh: 119, unit: "per site/night" },
    ]),
    sections: [section("Understand the charging unit", ["A per-person hike-in fee and a per-site powered rate cannot be ranked without the group size. Add extra-person, vehicle, park-entry and booking charges before comparing.", "Facilities matter. Toilets, showers, power, water, laundry, dump points and a convenient town location can replace other spending." ]), section("Promotions are not normal rates", ["Commercial examples may require a minimum stay, restricted dates or two-person occupancy. Record them as observed offers rather than a guaranteed national average.", "Government fees also change by financial year and category. Open the exact campground page before travelling."], ["Check the fee unit", "Confirm inclusions", "Read arrival conditions"]), section("Use paid and simple nights deliberately", ["A low-facility night works when the vehicle and supplies are ready. A serviced night is valuable when tanks, batteries, laundry and people all need a reset.", "Keep a paid legal alternative saved near popular free or low-cost areas. Full sites and changed local restrictions should not force an unsafe late drive."])],
    sources: [{ label: "Parks Victoria fees 2025–27", url: "https://www.parks.vic.gov.au/-/media/project/pv/main/parks/documents/about-us/fees-and-charges-schedule-2025-26-to-2026-27pdf.pdf" }, { label: "BIG4 Harrington offer", url: "https://www.big4.com.au/caravan-parks/nsw/north-coast/colonial-holiday-park/deals" }, { label: "BIG4 Sandstone Point offer", url: "https://www.big4.com.au/caravan-parks/qld/greater-brisbane/sandstone-point-holiday-resort/deals/follow-the-sunshine-sale-powered-sites" }]
  }),
  article({
    slug: "australia-road-trip-fuel-cost-2026", title: "Australian road-trip fuel costs in 2026", description: "Calculate petrol or diesel from distance and consumption, using current official city benchmarks and a remote-road margin.", category: "Costs & budget", region: "Australia", readTime: 12,
    places: ["Sydney", "Melbourne", "Brisbane", "Adelaide", "Perth"], imageAlt: "Vehicle refuelling during an Australian road trip", intro: "Fuel is where distance becomes money. Official Fuel Plan data for 5 August 2026 put the five-largest-city average at A$2.08 per litre for petrol and A$2.47 for diesel, while remote prices can be materially higher.",
    priceTable: priceTable("Calculated from Fuel Plan’s 5 August 2026 five-largest-city averages: A$2.08/L petrol and A$2.47/L diesel.", [
      { label: "Petrol", audLow: 2.08, unit: "per litre" }, { label: "Diesel", audLow: 2.47, unit: "per litre" },
      { label: "Petrol car, 1,000 km at 8 L/100 km", audLow: 166.4, unit: "trip" }, { label: "Petrol campervan, 1,000 km at 12 L/100 km", audLow: 249.6, unit: "trip" },
      { label: "Diesel rig, 1,000 km at 15 L/100 km", audLow: 370.5, unit: "trip" },
    ]),
    sections: [section("The calculation", ["Multiply kilometres by litres per 100 kilometres, divide by 100, then multiply by the price per litre. A 1,000 km drive at 12 L/100 km uses 120 litres.", "Use the vehicle’s real loaded consumption when possible. Roof loads, towing, wind, speed, terrain and air conditioning can move it beyond the brochure figure." ]), section("Capital averages are not remote quotes", ["The official city benchmark is a transparent starting point. Remote roadhouses carry different costs and are too important to skip merely to chase a lower price farther ahead.", "Fill conservatively, know the next dependable service and keep fuel stops inside the trip plan."], ["Use loaded consumption", "Add a remote margin", "Never run the tank to empty"]), section("Reduce cost without reducing safety", ["Slower, smoother driving and correct tyre pressures can help, but pressures must suit the vehicle, load and manufacturer guidance. Never coast unsafely or carry fuel in an unsuitable container.", "The biggest saving is often fewer unnecessary kilometres. Group nearby stops and avoid crossing the same city or remote section repeatedly."])],
    sources: [{ label: "Australian Government Fuel Plan statistics", url: "https://fuelplan.gov.au/fuel-statistics" }, { label: "ACCC weekly fuel monitoring", url: "https://www.accc.gov.au/about-us/publications/serial-publications/weekly-fuel-price-monitoring-reports" }, { label: "Reserve Bank of Australia exchange rates", url: "https://www.rba.gov.au/statistics/frequency/exchange-rates.html" }]
  }),
  article({
    slug: "public-transport-costs-australia-2026", title: "Public transport costs across Australian cities in 2026", description: "Compare Brisbane, Perth, Melbourne and Sydney fares without confusing per-trip prices with daily caps.", category: "Costs & budget", region: "Capital cities", readTime: 11,
    places: ["Brisbane", "Perth", "Melbourne", "Sydney"], imageAlt: "Public transport in an Australian city", intro: "Australian city fares use different rules, payment methods and caps. A flat Queensland journey, a Perth DayRider and Sydney’s daily cap answer different questions, so compare the full day you expect to travel.",
    priceTable: priceTable("Adult benchmarks checked 12 August 2026. Airport services, eligibility, concessions and payment methods can change the result.", [
      { label: "Queensland Translink journey", audLow: 0.5, unit: "per journey" }, { label: "Perth SmartRider Autoload fare", audLow: 2.8, unit: "standard journey" },
      { label: "Perth DayRider", audLow: 7, unit: "per day" }, { label: "Victoria temporary full-fare cap", audLow: 5.7, unit: "per day" },
      { label: "Sydney Mon–Thu cap", audLow: 19.3, unit: "per day" }, { label: "Sydney Fri/weekend/holiday cap", audLow: 9.65, unit: "per day" },
      { label: "Sydney weekly cap", audLow: 50, unit: "per week" },
    ]),
    sections: [section("Compare the same unit", ["A fare per journey is not a daily maximum. Count the expected trips, understand transfers and then apply the operator’s current cap rules.", "Use the accepted payment method correctly. Contactless, stored-value and cash fares can differ, and tapping errors can remove a cap or create an incomplete trip." ]), section("Airport travel is often separate", ["Private or station-access charges may sit outside ordinary public-transport pricing. Brisbane’s Airtrain is excluded from Queensland’s 50-cent fare, while Sydney Airport charges an access fee in addition to the rail fare.", "Price the airport leg separately before deciding whether rail, bus, shuttle, taxi or rideshare works best."], ["Check airport exclusions", "Tap on and off correctly", "Confirm temporary fare periods"]), section("Use transport to avoid city driving", ["Parking, tolls and unfamiliar traffic can make public transport valuable even when several people share a car. Compare the full vehicle cost, not only the train fare.", "Leave the campervan or caravan at a legal base where possible and use city transport for dense central areas."])],
    sources: [{ label: "Queensland 50-cent fares", url: "https://translink.com.au/tickets-and-fares/50-cent-fares" }, { label: "Transperth fares", url: "https://www.transperth.wa.gov.au/Tickets-Fares/Fares" }, { label: "Transport Victoria temporary half-price fares", url: "https://transport.vic.gov.au/news-and-resources/news/public-transport-now-half-price-for-everyone" }, { label: "Transport for NSW adult Opal fares", url: "https://transportnsw.info/tickets-fares/fares/adult-opal-fares" }]
  }),
  article({
    slug: "domestic-flight-costs-australia-2026", title: "Domestic flight costs in Australia: realistic 2026 sale floors", description: "Observed fares for short, northbound and transcontinental routes, plus the extras that turn a headline into a total.", category: "Costs & budget", region: "Australia", readTime: 11,
    places: ["Sydney", "Melbourne", "Cairns", "Perth", "Uluṟu", "Darwin"], imageAlt: "Aircraft flying over the Australian landscape", intro: "Australia’s scale makes flying attractive, but the cheapest advertised seat is a dated sale example rather than a standing fare. These observed 2026 floors show the shape of the market before baggage, seats and peak dates.",
    priceTable: priceTable("Expired 2026 promotional one-way fare examples. They demonstrate observed sale floors, not current bookable quotes.", [
      { label: "Sydney–Ballina", audLow: 49, unit: "one-way sale example" }, { label: "Melbourne–Sydney", audLow: 105, unit: "one-way sale example" },
      { label: "Sydney–Cairns", audLow: 115, unit: "one-way sale example" }, { label: "Melbourne–Uluṟu", audLow: 115, unit: "one-way sale example" },
      { label: "Sydney–Darwin", audLow: 167, unit: "one-way sale example" }, { label: "Sydney–Perth", audLow: 245, unit: "one-way sale example" },
    ]),
    sections: [section("Sale floor versus trip total", ["Add checked baggage, seat selection, payment charges, airport transport and the cost of reaching or replacing the vehicle. A cheap flight can still be the expensive option for a gear-heavy trip.", "Compare matching dates and luggage rather than two headline numbers." ]), section("Distance changes the value", ["Flying can save days across the continent, while a short east-coast sector may compete with rail, coach or a one-way vehicle plan. Time has a budget value too.", "One-way vehicle fees and restricted rental roads can matter more than the ticket."], ["Price baggage", "Include airport transfers", "Check one-way vehicle fees"]), section("Use sale examples honestly", ["The table records published promotions from Virgin Australia and Jetstar. Both had limited inventory and travel conditions, so no reader should expect the same fare today.", "Search the exact dates directly with carriers and compare the complete checkout amount before changing the route."])],
    sources: [{ label: "Virgin Australia July 2026 sale examples", url: "https://www.virginaustralia.com/au/en/newsroom/2026/7/virgin-australia-treats-aussie-travellers-to-one-million-sale-fares-starting-from-49/" }, { label: "Jetstar Northern Territory sale examples", url: "https://www.jetstar.com/au/en/newsroom/jetstar-launches-five-day-darwin-and-uluru-sale-with-fares-from-115" }, { label: "Reserve Bank of Australia exchange rates", url: "https://www.rba.gov.au/statistics/frequency/exchange-rates.html" }]
  }),
  article({
    slug: "bus-train-costs-australia-2026", title: "Long-distance bus and train costs in Australia", description: "Compare an interstate coach, a Queensland transport train and a luxury rail journey without pretending they are the same product.", category: "Costs & budget", region: "Australia", readTime: 11,
    places: ["Sydney", "Melbourne", "Brisbane", "Cairns", "Adelaide", "Darwin"], imageAlt: "Long-distance train travelling through Australia", intro: "Australia’s long-distance transport ranges from a functional overnight coach to an all-inclusive rail experience. Price, travel time, sleeping arrangement and inclusions must be compared together.",
    priceTable: priceTable("Dated provider benchmarks. Queensland Rail’s figure is from the indexed 2025–26 sheet; request the current 2026–27 fare before booking.", [
      { label: "Sydney–Melbourne coach", audLow: 135, unit: "advertised from" }, { label: "Cairns–Brisbane rail", audLow: 389.25, audHigh: 519, unit: "2025–26 benchmark" },
      { label: "The Ghan Adelaide–Darwin", audLow: 6290, unit: "2026 experiential example" },
    ]),
    sections: [section("Transport and experience", ["A coach seat and an all-inclusive sleeper train do not solve the same need. One buys movement; the other may bundle accommodation, meals and excursions.", "List what the fare includes before comparing it with flights, driving or several hotel nights." ]), section("Time, sleep and arrival", ["An overnight service may save a room but deliver a poor night for someone who cannot sleep seated. Daylight arrival and onward transport also matter.", "Check luggage limits, bicycle or surfboard rules and the distance between the terminal and the actual destination."], ["Confirm the current timetable", "Price the terminal transfer", "Read luggage limits"]), section("Treat old fare sheets carefully", ["Queensland Rail directs travellers to current information, while the publicly indexed sheet provides only a dated benchmark. Do not reproduce it as a current guaranteed fare.", "Industrial action, track work and seasonal timetables can change service. Confirm directly before building fixed bookings around the arrival."])],
    sources: [{ label: "Greyhound Sydney to Melbourne", url: "https://www.greyhound.com.au/buses/sydney-to-melbourne" }, { label: "Queensland Rail travel information", url: "https://www.queenslandrailtravel.com.au/toolbox/TravelInformation" }, { label: "Queensland Rail 2025–26 Spirit of Queensland sheet", url: "https://www.queenslandrailtravel.com.au/toolbox/TravelInformation/Documents/Fare%20sheets/Spirit%20of%20Queensland%20fares%20-%202025-26.pdf" }, { label: "2026 Ghan example", url: "https://www.greattrains.com.au/the-ghan/adelaide-to-darwin" }]
  }),
  article({
    slug: "driving-in-australia-road-rules-visitors", title: "Driving in Australia for the first time: essential road rules", description: "Drive on the left, understand speed and restraint rules, and know why licence conditions matter across state borders.", category: "Rules & safety", region: "Australia", readTime: 12,
    places: ["New South Wales", "Victoria", "Queensland", "Western Australia"], imageAlt: "Australian road seen from the left-hand driving position", intro: "Australia drives on the left, but safe visitor driving involves more than remembering the side of the road. Speed, alcohol, mobile devices and licence conditions all need a cautious, jurisdiction-aware approach.",
    sections: [section("Left-side habits", ["Take extra care after stops, at turns and when entering roundabouts, when old right-side habits can return. Keep the driver near the centre line and the passenger side near the kerb.", "Set navigation, mirrors and controls before moving. If orientation feels wrong, stop legally and reset rather than correcting while driving." ]), section("Speed, restraints and devices", ["A posted limit is the legal maximum in good conditions, not a target. Slow for weather, visibility, wildlife, gravel and the vehicle’s size.", "Every occupant needs the correct seating position and restraint. Portable-device rules and exceptions vary, so the safest practice is not to touch a phone while driving."], ["Drive left", "Buckle every occupant", "Configure navigation before moving"]), section("Alcohol and jurisdiction differences", ["Never present 0.05 as a universal allowance. Learner and provisional drivers can require zero BAC, while some heavy or passenger-vehicle categories have lower limits.", "The Australian Road Rules are a national model, but every state and territory enacts its own law and can add differences. Read the authority for the place you are driving."])],
    sources: [{ label: "Australian Road Rules overview", url: "https://www.infrastructure.gov.au/infrastructure-transport-vehicles/roads/road-safety/australian-road-rules" }, { label: "Tourists driving in Victoria", url: "https://transport.vic.gov.au/road-and-active-transport/road-rules-and-safety/tourists-driving-in-victoria" }, { label: "NSW alcohol and drugs", url: "https://www.nsw.gov.au/driving-boating-and-transport/roads-safety-and-rules/safe-driving/alcohol-and-drugs" }]
  }),
  article({
    slug: "overseas-driver-licence-australia-state-guide", title: "Can you drive in Australia with an overseas licence?", description: "A state-by-state visitor guide to validity, translations, IDPs, vehicle class and conversion deadlines.", category: "Rules & safety", region: "Australia", readTime: 12,
    places: ["New South Wales", "Victoria", "Queensland", "Western Australia"], imageAlt: "Driver holding an overseas licence beside a rental vehicle", intro: "There is no single nationwide deadline for driving on an overseas licence. Visitor status, residency, language, vehicle class and the state or territory all affect what documents and time limits apply.",
    sections: [section("Visitor rules are jurisdiction-specific", ["NSW temporary visitors can generally drive for up to six months when eligible, while Victoria also describes a six-month visitor period. Queensland and Western Australia use their own validity and residency rules.", "Do not carry one state’s rule across a border. Open the authority page for every jurisdiction on the route." ]), section("Translations and document conditions", ["A non-English licence may require an approved English translation or International Driving Permit. Carry the physical documents required and obey every condition on the original licence.", "An IDP supports the home licence; it does not replace an expired, suspended or otherwise invalid licence."], ["Carry the original licence", "Arrange an approved translation", "Check every state"]), section("Vehicle class matters", ["A standard car class in NSW and Queensland generally covers no more than 4.5 tonnes GVM and 12 occupants including the driver. A larger motorhome may require a different authorised class.", "Rental permission and insurance do not override licensing law. Confirm all three before accepting the vehicle."])],
    sources: [{ label: "NSW overseas visitors", url: "https://www.nsw.gov.au/driving-boating-and-transport/driver-and-rider-licences/visiting-or-moving-to-nsw/visiting-from-overseas-or-interstate" }, { label: "Queensland overseas licences", url: "https://www.qld.gov.au/transport/licensing/driver-licensing/overseas/driving" }, { label: "WA overseas visitors", url: "https://www.transport.wa.gov.au/licensing/drivers-licence/visit-move-wa/visiting-overseas-interstate" }, { label: "Tourists driving in Victoria", url: "https://transport.vic.gov.au/road-and-active-transport/road-rules-and-safety/tourists-driving-in-victoria" }]
  }),
  article({
    slug: "australian-road-signs-visitors-guide", title: "Australian road signs visitors should know", description: "Regulatory, warning, advisory and roadwork signs explained for people starting an Australian road trip.", category: "Rules & safety", region: "Australia", readTime: 13,
    places: ["Queensland", "Northern Territory", "Roadworks", "Remote highways"], imageAlt: "Australian warning and regulatory road signs", intro: "Australian signs use familiar shapes and colours, but a visitor needs to distinguish a legal instruction from a hazard warning or advisory speed. Temporary traffic control matters just as much as a permanent sign.",
    sections: [section("Regulatory signs", ["Stop, Give Way, speed limit, Keep Left, No Entry, prohibited turns, roundabouts and shared zones create legal requirements. A Stop sign requires a complete stop.", "Give Way requires slowing and stopping when necessary, then applying the priority rule for the intersection." ]), section("Warnings and advisory speeds", ["Warning signs identify bends, merging or narrowing lanes, animals, unsealed surfaces, floodways and railway crossings. The hazard changes how you drive even when the posted maximum stays the same.", "A regulatory speed sign is not the same as an advisory speed displayed for a bend or crest. Slow to the conditions and vehicle."], ["Read the shape and colour", "Do not treat advisory speed as a target", "Expect animals near dusk"]), section("Roadworks and road trains", ["Temporary speed limits, traffic lights and traffic-controller directions at roadworks must be obeyed. Conditions can change between trips.", "A yellow ROAD TRAIN or LONG VEHICLE panel attached to a truck identifies that vehicle. Give it space; do not mistake the panel for a roadside direction."])],
    sources: [{ label: "Queensland regulatory signs", url: "https://www.qld.gov.au/transport/safety/signs/regulatory" }, { label: "Queensland warning signs", url: "https://www.qld.gov.au/transport/safety/signs/warning" }, { label: "Queensland roadwork signs", url: "https://www.qld.gov.au/transport/safety/signs/roadworks" }, { label: "Northern Territory road signs", url: "https://nt.gov.au/driving/safety/road-signs" }]
  }),
  article({
    slug: "campervan-driving-australia-safety-guide", title: "Campervan driving in Australia: size, safety and legal limits", description: "Check licence class, vehicle dimensions, restraints and road exclusions before the first long driving day.", category: "Rules & safety", region: "Australia", readTime: 12,
    places: ["Rental depots", "City streets", "Gravel roads", "Remote highways"], imageAlt: "Campervan travelling on an Australian highway", intro: "A campervan may feel like a large car until braking, crosswind or a low branch exposes its real size. The safe handover begins with dimensions, loaded weight, licence class and rental conditions.",
    sections: [section("Know the vehicle before moving", ["Record the height, length and GVM, locate the fuel type and learn the mirrors, blind spots and controls. A vehicle above 4.5 tonnes may fall outside an ordinary car licence.", "Confirm tyre, awning, roof, gas and interior stowage procedures with the operator." ]), section("Everyone travels in a proper seat", ["Beds and living areas are not passenger positions while moving. Every occupant must use an approved seat and the required restraint.", "Secure loose items before every drive. A cupboard or bottle becomes dangerous under sudden braking."], ["Record vehicle height", "Secure the cabin", "Use proper restraints"]), section("Drive for the loaded vehicle", ["Allow more stopping distance, turn smoothly and slow before bends, gravel, crosswinds and narrow shoulders. A legal maximum can still be unsafe.", "Rental exclusions, insurance conditions and government road rules are separate requirements. Permission from one does not cancel the others."])],
    sources: [{ label: "NSW overseas licence vehicle classes", url: "https://www.nsw.gov.au/driving-boating-and-transport/driver-and-rider-licences/visiting-or-moving-to-nsw/visiting-from-overseas-or-interstate" }, { label: "Queensland overseas licence vehicle classes", url: "https://www.qld.gov.au/transport/licensing/driver-licensing/overseas/driving" }, { label: "NT driving safety checklist", url: "https://nt.gov.au/driving/safety/driving-safety-checklist" }]
  }),
  article({
    slug: "towing-caravan-australia-road-rules", title: "Towing a caravan in Australia: weights, speed and state differences", description: "A practical guide to loaded limits, couplings, braking room and the towing rules that change at state borders.", category: "Rules & safety", region: "Australia", readTime: 13,
    places: ["Western Australia", "New South Wales", "South Australia", "Remote highways"], imageAlt: "Car and caravan travelling on an Australian road", intro: "Safe towing starts with the actual loaded combination, not the empty caravan brochure. Manufacturer limits, ball load, licence conditions and jurisdiction rules all need to agree.",
    sections: [section("Weights and connection", ["Keep the loaded caravan within the tow vehicle, towbar, coupling and manufacturer limits. Secure the load and inspect chains, hatches, tyres, brakes and lights.", "Repeat the inspection during long trips. Heat, vibration and rough surfaces can expose a problem that was not visible at departure." ]), section("Nobody rides in the caravan", ["A towed caravan or trailer is not a passenger compartment. Everyone travels in an approved vehicle seating position with the correct restraint.", "Extra length and mass require longer stopping distance, wider cornering lines and smooth steering and braking."], ["Confirm every limit", "Check the coupling", "No passengers in the caravan"]), section("Speed rules vary", ["Western Australia limits a vehicle towing a trailer or caravan to 100 km/h and has a 60-metre following rule behind certain heavy or towing vehicles unless overtaking.", "NSW’s cited 100 km/h cap applies when the towing vehicle or combination exceeds 4.5 tonnes. Never turn one jurisdiction’s rule into a nationwide towing speed."])],
    sources: [{ label: "WA towing rules", url: "https://www.wa.gov.au/organisation/road-safety-commission/towing" }, { label: "NSW towing guidance", url: "https://www.nsw.gov.au/driving-boating-and-transport/roads-safety-and-rules/vehicle-safety-and-compliance/towing-a-caravan" }, { label: "South Australia caravan towing", url: "https://www.sa.gov.au/topics/driving-and-transport/vehicles/vehicle-standards-and-modifications/towing-a-caravan" }]
  }),
  article({
    slug: "driving-with-road-trains-australia", title: "How to share Australian roads with road trains", description: "Overtaking, dust, stopping distance and single-lane-road behaviour around vehicles up to 60 metres long.", category: "Rules & safety", region: "Outback Australia", readTime: 12,
    places: ["Northern Territory", "Western Australia", "Pilbara", "Outback highways"], imageAlt: "Road train on a remote Australian highway", intro: "A road train can be roughly 27.5 to 60 metres long. It needs space to stop, turn and pass, and the safest driver is predictable rather than helpful in an improvised way.",
    sections: [section("Following and overtaking", ["Stay well back, especially on unsealed roads where dust can erase visibility. Never pass without a long, fully visible clear stretch.", "Do not overtake a turning road train or cut in after passing. Its stopping distance is much greater than a car’s." ]), section("When a road train passes you", ["Northern Territory guidance says to maintain speed and keep left, then slow only once the truck has moved out to pass. Sudden early slowing can disrupt the manoeuvre.", "Do not rely on informal flashing lights or UHF directions as if they were legal traffic control."], ["Be predictable", "Keep left", "Leave a long gap"]), section("Single-lane and unsealed roads", ["On an NT single-lane highway, slow and pull off, moving slowly on the shoulder for an approaching road train when safe. Expect dust and loose stones.", "Choose a safe place and avoid a soft, steep or damaged shoulder. Conditions and jurisdiction guidance still control the decision."])],
    sources: [{ label: "NT driving with road trains", url: "https://nt.gov.au/driving/safety/driving-with-road-trains" }, { label: "Main Roads WA long-distance driving", url: "https://www.mainroads.wa.gov.au/travel-information/driving-in-wa/long-distance-driving/" }, { label: "WA towing rules", url: "https://www.wa.gov.au/organisation/road-safety-commission/towing" }]
  }),
  article({
    slug: "australia-road-trip-fatigue-wildlife-safety", title: "Fatigue, wildlife and night driving on Australian road trips", description: "Recognise fatigue early, plan real breaks and reduce the risk of dawn, dusk and remote-road driving.", category: "Rules & safety", region: "Australia", readTime: 12,
    places: ["Victoria", "Queensland", "Northern Territory", "Remote Western Australia"], imageAlt: "Kangaroo beside a quiet Australian road at dusk", intro: "Long distances do not make fatigue inevitable; tight itineraries do. Sleep is the only cure, wildlife is harder to see around dawn and dusk, and a daylight arrival gives every backup more room.",
    sections: [section("Recognise fatigue before it becomes a crisis", ["Yawning, heavy eyes, lane drift, forgotten kilometres and inconsistent speed are warnings to stop. Music, open windows and caffeine do not replace sleep.", "Plan a break at least every two hours. Victorian guidance recommends no more than eight hours of driving in a 24-hour period." ]), section("Wildlife and night", ["Animals and livestock are particularly active around dawn and dusk. Reduce speed when animals are near the road and avoid swerving, which can cause a rollover or another collision.", "Prefer daylight on unfamiliar roads and finish before fatigue begins choosing the speed, lane position or next stop."], ["Break every two hours", "Avoid dawn and dusk", "Sleep before continuing"]), section("Remote breakdown preparation", ["Carry extra water, food, fuel margin and an appropriate communication method where services are sparse. Tell someone the route and expected arrival.", "Official WA remote-travel guidance says to remain with the vehicle if stranded. A vehicle provides shelter and is easier for rescuers to find."])],
    sources: [{ label: "Transport Victoria fatigue guidance", url: "https://transport.vic.gov.au/road-and-active-transport/road-rules-and-safety/fatigue-and-driving" }, { label: "Queensland long-trip guidance", url: "https://www.qld.gov.au/transport/safety/holiday-travel/long-trips" }, { label: "NT fatigue guidance", url: "https://nt.gov.au/driving/safety/fatigue-and-driving" }, { label: "Explore Parks WA remote travel", url: "https://exploreparks.dbca.wa.gov.au/travelling-remote-locations" }]
  }),
  article({
    slug: "australia-road-rules-state-differences", title: "Australian road rules that change across states and territories", description: "Default speeds, towing, devices and licence conditions compared without turning local rules into national advice.", category: "Rules & safety", region: "Australia", readTime: 13,
    places: ["Queensland", "Victoria", "Western Australia", "Northern Territory", "South Australia"], imageAlt: "Australian highway crossing a state border", intro: "Australian road rules are broadly consistent, but the legislation belongs to each state and territory. Default speeds, mobile-device exceptions, provisional restrictions, towing and overseas-licence periods can change at a border.",
    sections: [section("Model rules and local law", ["The Australian Road Rules provide a national model. Jurisdictions enact and amend their own versions, so a summary cannot replace the current local authority.", "Posted signs, licence conditions and lower vehicle-specific limits always take priority over a general default." ]), section("Default unsigned speed examples", ["Queensland and Victoria describe 50 km/h in built-up areas and 100 km/h outside built-up areas. Western Australia states 50 km/h built-up and 110 km/h on open roads.", "The Northern Territory generally uses 60 km/h in built-up areas unless gazetted lower and 110 km/h outside, with signed 130 km/h sections on specified highways."], ["Follow posted signs", "Check before crossing borders", "Apply vehicle limits"]), section("The other differences that matter", ["Mobile-device exceptions, learner and provisional conditions, towing speeds and overseas-licence conversion periods all vary. A rental company can also impose tighter road exclusions.", "Save direct state authority links before travel and review them whenever the vehicle, licence status or jurisdiction changes."])],
    sources: [{ label: "Australian Road Rules overview", url: "https://www.infrastructure.gov.au/infrastructure-transport-vehicles/roads/road-safety/australian-road-rules" }, { label: "Queensland speed limits", url: "https://www.qld.gov.au/transport/safety/rules/speed-limits" }, { label: "Victoria speed limits", url: "https://transport.vic.gov.au/road-and-active-transport/road-rules-and-safety/speed-limits" }, { label: "WA traffic rules", url: "https://transport.wa.gov.au/licensing/drivers-licence/driver-rules-penalties-infringements/traffic-infringements" }, { label: "NT speed limits", url: "https://nt.gov.au/driving/safety/speed-limits" }]
  }),
];
