import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Calculator, CircleDollarSign } from "lucide-react";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { CurrencyConverter } from "@/components/currency-converter";
import { FuelCalculator } from "@/components/fuel-calculator";
import { currencyRates } from "@/lib/currency";

export const metadata: Metadata = { title: "Australia road trip tools", description: "Convert Australian prices and calculate road trip fuel costs with transparent dated reference rates.", alternates: { canonical: "/tools" } };

export default function ToolsPage() {
  const script = `(function(){const rates=${JSON.stringify(currencyRates)};const currencies=Object.keys(rates);const money=(value,currency)=>new Intl.NumberFormat('en-AU',{style:'currency',currency,maximumFractionDigits:currency==='JPY'||currency==='KRW'?0:value<10?2:0}).format(value);const currencyTool=document.querySelector('[data-currency-tool]');const updateCurrency=()=>{const amount=Number(currencyTool.querySelector('[data-currency-amount]').value);const from=currencyTool.querySelector('[data-currency-from]').value;const to=currencyTool.querySelector('[data-currency-to]').value;currencyTool.querySelector('[data-currency-output]').textContent=Number.isFinite(amount)&&amount>=0?money(amount/rates[from]*rates[to],to):'Enter a valid amount'};currencyTool.addEventListener('input',updateCurrency);currencyTool.addEventListener('change',updateCurrency);const fuelTool=document.querySelector('[data-fuel-tool]');const updateFuel=()=>{const distance=Number(fuelTool.querySelector('[data-fuel-distance]').value);const consumption=Number(fuelTool.querySelector('[data-fuel-consumption]').value);const price=Number(fuelTool.querySelector('[data-fuel-price]').value);const valid=[distance,consumption,price].every(value=>Number.isFinite(value)&&value>=0);const litres=distance*consumption/100;fuelTool.querySelector('[data-fuel-output]').textContent=valid?litres.toFixed(1)+' L · A$'+(litres*price).toFixed(2):'Enter valid values'};fuelTool.addEventListener('input',updateFuel);})();`;
  return <><Header/><main><section className="page-hero tools-hero"><p className="eyebrow">Useful numbers</p><h1>Road trip tools.<br/>No mystery maths.</h1><p>Quick planning calculators for Australian prices and driving costs. Every assumption stays visible so you can replace it with the number that fits your route.</p></section><section className="tools-shell"><CurrencyConverter/><FuelCalculator/><section className="tools-reading"><div><CircleDollarSign/><h2>Build the budget from current benchmarks.</h2></div><p>The tools calculate exactly what you enter. Our cost guides explain where the starting figures came from, when they were checked and what can change the final price.</p><Link href="/guides" className="text-link">Explore cost guides <ArrowRight/></Link></section><section className="tools-note"><Calculator/><p>These calculators are planning aids, not live booking, fuel-station or foreign-exchange quotes. Confirm current prices before purchase.</p></section></section></main><Footer/><script data-static-tools dangerouslySetInnerHTML={{__html:script}}/></>;
}
